### ISSUE TITLE
Notes Panel

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/volunteer#16]
On the right side of the screen, there should be a sidebar which displays information including nonclassified user information (gender, etc.), the volunteer alias described in ProjectCopilot/mailroom#46, and any notes the user might take. The notes should include a list of important fields, which will be described by a JSON file. (We will research and figure out what information is most urgent for the volunteers to collect. For now, it should be generalized.) It should then include a text area where volunteers can write any information they think might be helpful. This panel should also include the information release button described in #17.

**Comment by gmittal** [comment]
Should look something like the right user info pane in Facebook Messenger:

![screen shot 2016-07-29 at 6 38 39 pm](https://cloud.githubusercontent.com/assets/2015126/17307369/97c9e81e-57e9-11e6-923c-a3f7f445ebb2.png)

The current UI only has the two left most panes implemented.

**Comment by gmittal** [comment]
@srustagi What's the status on this?

**Comment by gmittal** [comment]
It's be really nice to use this to solve the notes problem. 

https://github.com/yabwe/medium-editor

**Comment by gmittal** [comment]
Closed through #33
