### ISSUE TITLE
Set up unit testing

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/volunteer#2]
It's best that we integrate testing from the get-go. I've had good experiences with [Mocha](https://mochajs.org/). Your thoughts?

**Comment by gmittal** [comment]
Unit tests sound good. I've never used Mocha, but it looks pretty similar to most other unit testing frameworks I've seen.

**Comment by ankitr** [comment]
Cool. Let's try to have 100% test coverage. Once we have this going I'll set up continuous integration with Travis or CircleCI or something.

**Comment by gmittal** [comment]
Removing unit tests; volunteer is comprised of only UI-based functions and Firebase event handlers.

**Comment by ankitr** [comment]
At a later point, it might be worth implementing headless chrome tests, but I think that's very low priority. Let's just keep it in mind.
